/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.alumnogui;

import dao.AlumnoDAOSQL;
import dao.AlumnoDAOTXT;
import dao.DAO;
import dao.DAOException;
import dao.DAOFactory;
import dao.DAOFactoryException;
import exceptions.DniInvalidoException;
import exceptions.NombreInvalidoException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import persona.Alumno;

/**
 *
 * @author g.guzman
 */
@SuppressWarnings({"serial", "this-escape"})
public class AlumnoGUI extends javax.swing.JFrame {

    private static final String DEFAULT_DB_URL = "jdbc:mysql://localhost:3306/universidad_caba";
    private static final String DEFAULT_DB_USER = "root";
    private static final String DEFAULT_DB_PWD = "root";

    private DAO<Alumno, Integer> dao;
    private AlumnoDAOTXT daoTXT;
    private AlumnoDAOSQL daoSQL;
    private List<Alumno> alumnos;
    private AlumnosModel alumnosModel;

    /**
     * Creates new form AlumnoGUI
     */
    public AlumnoGUI() {
        initComponents();
        setLocationRelativeTo(null);
        bdPanel.setVisible(false);

        //TableModel alumnosModel = new AlumnosModel();
        alumnosModel = new AlumnosModel();
        alumnosTable.setModel(alumnosModel);
        verEliminadosCheckBox.setSelected(false);
        userTextField.setText(DEFAULT_DB_USER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        alumnosTable = new javax.swing.JTable();
        botoneraPanel = new javax.swing.JPanel();
        crearButton = new javax.swing.JButton();
        modificarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        consultarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        repoComboBox = new javax.swing.JComboBox<>();
        txtPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pathfileTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        bdPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        userTextField = new javax.swing.JTextField();
        connDBButton = new javax.swing.JButton();
        verEliminadosCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        alumnosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(alumnosTable);

        crearButton.setText("Crear");
        crearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearButtonActionPerformed(evt);
            }
        });

        modificarButton.setText("Modificar");
        modificarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarButtonActionPerformed(evt);
            }
        });

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        consultarButton.setText("Consultar");
        consultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botoneraPanelLayout = new javax.swing.GroupLayout(botoneraPanel);
        botoneraPanel.setLayout(botoneraPanelLayout);
        botoneraPanelLayout.setHorizontalGroup(
            botoneraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoneraPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(botoneraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(botoneraPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(botoneraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modificarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(crearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(eliminarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consultarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        botoneraPanelLayout.setVerticalGroup(
            botoneraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoneraPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crearButton)
                .addGap(18, 18, 18)
                .addComponent(modificarButton)
                .addGap(18, 18, 18)
                .addComponent(eliminarButton)
                .addGap(18, 18, 18)
                .addComponent(consultarButton)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel1.setText("Repositorio:");

        repoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TXT", "BD" }));
        repoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repoComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Archivo:");

        pathfileTextField.setEditable(false);
        pathfileTextField.setEnabled(false);

        browseButton.setText("...");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout txtPanelLayout = new javax.swing.GroupLayout(txtPanel);
        txtPanel.setLayout(txtPanelLayout);
        txtPanelLayout.setHorizontalGroup(
            txtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(pathfileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(browseButton)
                .addGap(30, 30, 30))
        );
        txtPanelLayout.setVerticalGroup(
            txtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(browseButton)
                    .addComponent(pathfileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel3.setText("Usuario:");

        connDBButton.setText("Conectar");
        connDBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connDBButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bdPanelLayout = new javax.swing.GroupLayout(bdPanel);
        bdPanel.setLayout(bdPanelLayout);
        bdPanelLayout.setHorizontalGroup(
            bdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 337, Short.MAX_VALUE)
                .addComponent(connDBButton)
                .addContainerGap())
        );
        bdPanelLayout.setVerticalGroup(
            bdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connDBButton))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        verEliminadosCheckBox.setText("Ver Eliminados");
        verEliminadosCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEliminadosCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(repoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(100, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(verEliminadosCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(18, 18, 18)
                                .addComponent(botoneraPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(repoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(verEliminadosCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botoneraPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void repoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repoComboBoxActionPerformed
        if (repoComboBox.getSelectedIndex()==0) { // es TXT?
            if (daoTXT!=null) {
                dao = daoTXT;
            }
        } else {
            if (daoSQL != null) {
                dao = daoSQL;
            }
        }

        txtPanel.setVisible(repoComboBox.getSelectedIndex() == 0);
        bdPanel.setVisible(repoComboBox.getSelectedIndex() == 1);
        refrescarGrillaSiConectado();
    }//GEN-LAST:event_repoComboBoxActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        if (procesarEliminar()) {
            return;
        }
        int selectedRow = alumnosTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Nada Seleccionado", "Eliminar", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Alumno selectedAlu = alumnos.get(selectedRow);

        final int showConfirmDialog = JOptionPane.showConfirmDialog(this, "¿Confirma la eliminación de alumno " + selectedAlu.getNombre() + "?",
                "Confirmación", JOptionPane.OK_CANCEL_OPTION);
        if (showConfirmDialog == JOptionPane.OK_OPTION) {
            // dao.delete(selectedAlu.getDni());

            // Refresh de la vista
            alumnos.remove(selectedAlu);
            // o alumnos = dao.findAll();
            alumnosModel.fireTableDataChanged();
        }
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            if (daoTXT != null) {
                daoTXT.close();
            }
            // daoSQL.close();
        } catch (DAOException ex) {
            Logger.getLogger(AlumnoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        String fsv = "txt";
        JFileChooser fileChooser = new JFileChooser(fsv);
        final int showOpenDialog = fileChooser.showOpenDialog(this);
        if (showOpenDialog == JFileChooser.APPROVE_OPTION) {
            String pathfile = fileChooser.getSelectedFile().getAbsolutePath();
            pathfileTextField.setText(pathfile);
            
            Map<String, String> config = new HashMap<>();
            config.put(DAOFactory.TIPO_DAO, DAOFactory.TIPO_DAO_TXT);
            config.put(DAOFactory.PATH_FILE, pathfile);
            try {
                daoTXT = (AlumnoDAOTXT) DAOFactory.createDAO(config);
                dao = daoTXT;
                //((AlumnosModel)alumnosModel).setAlumnos(alumnos);

                alumnos = dao.findAll(false); // evaluar el chackbox
                alumnosModel.setAlumnos(alumnos);
                alumnosModel.fireTableDataChanged();

            } catch (DAOFactoryException | DAOException ex) {
                Logger.getLogger(AlumnoGUI.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    private void crearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearButtonActionPerformed
        if (dao == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un repositorio", "Crear",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        AlumnoDialog dialog = new AlumnoDialog(this, true, CrudOptionEnum.CREATE);
        dialog.setVisible(true);

        AlumnoDto dto = dialog.getDto();
        if (dto == null) {
            return;
        }

        try {
            Alumno aluToCreate = AlumnoMapper.dto2Alu(dto);
            dao.create(aluToCreate);
            refrescarGrillaSiConectado();
        } catch (DAOException | DniInvalidoException | NombreInvalidoException | IllegalArgumentException ex) {
            Logger.getLogger(AlumnoGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_crearButtonActionPerformed

    private void consultarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarButtonActionPerformed
        int selectedRow = alumnosTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Nada Seleccionado", "Consultar", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Alumno selectedAlu = alumnosModel.getAlumnoAt(selectedRow);
        if (selectedAlu == null) {
            JOptionPane.showMessageDialog(this, "Nada Seleccionado", "Consultar", JOptionPane.WARNING_MESSAGE);
            return;
        }

        AlumnoDialog dialog = new AlumnoDialog(this, true, CrudOptionEnum.READ);
        dialog.setDto(AlumnoMapper.alu2Dto(selectedAlu));
        dialog.setVisible(true);
    }//GEN-LAST:event_consultarButtonActionPerformed

    private void modificarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarButtonActionPerformed
        if (dao == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un repositorio", "Modificar",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int selectedRow = alumnosTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Nada Seleccionado", "Modificar", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Alumno selectedAlu = alumnosModel.getAlumnoAt(selectedRow);
        if (selectedAlu == null) {
            JOptionPane.showMessageDialog(this, "Nada Seleccionado", "Modificar", JOptionPane.WARNING_MESSAGE);
            return;
        }

        AlumnoDialog dialog = new AlumnoDialog(this, true, CrudOptionEnum.UPDATE);
        dialog.setDto(AlumnoMapper.alu2Dto(selectedAlu));
        dialog.setVisible(true);

        AlumnoDto dto = dialog.getDto();
        if (dto == null) {
            return;
        }

        try {
            Alumno aluToUpdate = AlumnoMapper.dto2Alu(dto);
            dao.update(aluToUpdate);
            refrescarGrillaSiConectado();
        } catch (DAOException | DniInvalidoException | NombreInvalidoException | IllegalArgumentException ex) {
            Logger.getLogger(AlumnoGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_modificarButtonActionPerformed

    private void connDBButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Map<String, String> config = new HashMap<>();
        config.put(DAOFactory.TIPO_DAO, DAOFactory.TIPO_DAO_SQL);
        config.put(DAOFactory.URL_DB, DEFAULT_DB_URL);
        config.put(DAOFactory.USER_DB, userTextField.getText());
        config.put(DAOFactory.PWD_DB, DEFAULT_DB_PWD);

        try {
            daoSQL = (AlumnoDAOSQL) DAOFactory.createDAO(config);
            dao = daoSQL;
            refrescarGrillaSiConectado();
        } catch (DAOFactoryException ex) {
            Logger.getLogger(AlumnoGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void verEliminadosCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {
        refrescarGrillaSiConectado();
    }

    private void refrescarGrillaSiConectado() {
        if (dao == null) {
            alumnosModel.limpiar();
            return;
        }

        try {
            alumnos = dao.findAll(verEliminadosCheckBox.isSelected());
            alumnosModel.setAlumnos(alumnos);
        } catch (DAOException ex) {
            Logger.getLogger(AlumnoGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private boolean procesarEliminar() {
        if (dao == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un repositorio", "Eliminar",
                    JOptionPane.WARNING_MESSAGE);
            return true;
        }

        int selectedRow = alumnosTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Nada Seleccionado", "Eliminar",
                    JOptionPane.WARNING_MESSAGE);
            return true;
        }

        Alumno selectedAlu = alumnosModel.getAlumnoAt(selectedRow);
        if (selectedAlu == null) {
            JOptionPane.showMessageDialog(this, "Nada Seleccionado", "Eliminar",
                    JOptionPane.WARNING_MESSAGE);
            return true;
        }

        final int showConfirmDialog = JOptionPane.showConfirmDialog(this,
                "Confirma la eliminacion de alumno " + selectedAlu.getNombre() + "?",
                "Confirmacion", JOptionPane.OK_CANCEL_OPTION);
        if (showConfirmDialog == JOptionPane.OK_OPTION) {
            try {
                dao.delete(selectedAlu.getDni());
                refrescarGrillaSiConectado();
            } catch (DAOException ex) {
                Logger.getLogger(AlumnoGUI.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlumnoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlumnoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlumnoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumnoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlumnoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable alumnosTable;
    private javax.swing.JPanel bdPanel;
    private javax.swing.JPanel botoneraPanel;
    private javax.swing.JButton browseButton;
    private javax.swing.JButton connDBButton;
    private javax.swing.JButton consultarButton;
    private javax.swing.JButton crearButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarButton;
    private javax.swing.JTextField pathfileTextField;
    private javax.swing.JComboBox<String> repoComboBox;
    private javax.swing.JPanel txtPanel;
    private javax.swing.JTextField userTextField;
    private javax.swing.JCheckBox verEliminadosCheckBox;
    // End of variables declaration//GEN-END:variables
}
